### PR TITLE
Pass the xkb `group` (a.k.a. `layout`) to `nk_bindings`

### LINKED ISSUE #56: [BUG] cannot change layout in rofi wayland
### Rofi version (rofi -v)

1.7.3+wayland1

### Configuration

https://gist.github.com/Tahvok/8d571e4a33ddc736c25b97fa7a3f5d81

### Launch command

rofi -show run

### Step to reproduce

I'm using sway, so I setup my layout configuration as follows:
```
input * {
    xkb_layout "us,us"
    xkb_variant ",colemak"
    xkb_options "grp:shift_toggle,caps:backspace"
}
```
All apps work fine, I can change the layout.

However, sway work only using qwerty - no matter if I launch rofi before changing the layout, or trying to change the layout when rofi is running.

### Expected behavior

rofi supports different keyboard layouts

### Actual behavior

Rofi always types in qwerty

### Additional information

_No response_

### LINKED ISSUE #92: [BUG] rofi-wayland doesn't follow changed keyboard layout
### Rofi version (rofi -v or git commit in case of build issue)

Version: 1.7.5+wayland2

### Configuration

https://gist.github.com/Nemo157/d3a398d548d5e11e868287b5abdb7135

### Theme

https://gist.github.com/Nemo157/41e5fcec566c5f8a2630cde5c80e9e4d

### Timing report

_No response_

### Launch command

rofi -show drun

### Step to reproduce

* Setup Hyprland with multiple keyboard layouts configured:

```
input {
  kb_layout = us,us
  kb_variant = ,dvp
  kb_options = caps:escape,compose:ralt,grp:win_space_toggle
}
```

* Launch rofi
* Switch layouts (using win/super+space as configured above) and notice that the input doesn't switch

### Expected behavior

Rofi should use the current keyboard layout when it changes

### Actual behavior

All input is as if the first keyboard layout remained selected

### Additional information

Tested on NixOS 23.05 with Hyprland 0.25.0+date=2023-05-03_f27873a

Testing upstream rofi under xwayland it does correctly switch layouts.

Testing 9d11a2b4a9095b3f0a092155f749900f7eb8e047 it similarly doesn't work there.

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

### PR DESCRIPTION
**Pull request by Nemo157**
The `group` is used by xkb to support switching between multiple layouts, without telling `nk_bindings` about this rofi always sees key presses as if they're in the first layout.

fixes #56

### CODE REVIEW

File: source/wayland/display.c [hunk 1]
```diff
@@ -459,7 +459,7 @@ static void wayland_keyboard_modifiers(void *data, struct wl_keyboard *keyboard,
                                        uint32_t mods_locked, uint32_t group) {
   wayland_seat *self = data;
   nk_bindings_seat_update_mask(wayland->bindings_seat, NULL, mods_depressed,
-                               mods_latched, mods_locked, 0, 0, 0);
+                               mods_latched, mods_locked, group, group, group);
```
Comment (lbonn) [inline source/wayland/display.c]: Looking at some docs, it looks like the locked layout/group would be enough: `[...] 0, 0, group);`

https://xkbcommon.org/doc/current/group__state.html#ga04e8eac0666cc64dee6f0d5a7a773a03

and

https://wayland-book.com/seat/keyboard.html#input-events

Also tested and it works :)

Comment (Nemo157) [reply source/wayland/display.c]: Makes sense, I guess wayland must be tracking state for the `grp:*_switch` options itself so they can be treated as just locked, and it doesn't look like latching is even possible.

**Comment by lbonn** [comment]
Thanks a lot!
