### PR TITLE
[WaylandWindow] Unmap surface before sending activation request

### LINKED ISSUE #117: [BUG] Rofi window mode does not seem to work anymore in Hyprland
### Rofi version (rofi -v or git commit in case of build issue)

Version: 1.7.5+wayland1-48-gd06095b5 (makepkg)

### Configuration

https://gist.github.com/LorenzoBettini/155b336f0a4ce302df771d7b542cebd1

### Theme

https://gist.github.com/LorenzoBettini/4a3dff4c44060e9b08951ee205e050a0

### Timing report

_No response_

### Launch command

rofi -show window

### Step to reproduce

* rofi -show window
* the list of windows appears
* select one but nothing happens

### Expected behavior

Once a window is selected it should be focused, and in case it's in another workspace, the workspace should also be switched

### Actual behavior

It used to work before but now nothing happens.

### Additional information

Maybe it's related to this:

```
wmctrl -l
Cannot get client list properties. 
(_NET_CLIENT_LIST or _WIN_CLIENT_LIST)
```

### Using wayland display server protocol

- [X] Yes, I use rofi with wayland support

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

### PR DESCRIPTION
**Pull request by alebastr**
Not tested on Hyprland. Lightly tested on Sway.

Let's hope that everything that can happen after `mode_result` doesn't cause a redraw or is sufficiently protected against not having a surface. Asynchronous list updates, queued events, etc...

Fixes lbonn/rofi#117

### CODE REVIEW

File: source/wayland/view.c [hunk 1]
```diff
@@ -423,7 +423,10 @@ static int wayland_rofi_view_calculate_window_height(RofiViewState *state) {
   return widget_get_desired_height(main_window, state->width);
 }
 
-static void wayland_rofi_view_hide(void) {}
+static void wayland_rofi_view_hide(void) {
+    display_surface_unmap();
+    display_early_cleanup();
```
Comment (lbonn) [inline source/wayland/view.c]: Suggestion on the organization of the different methods for more re-use:

```
display_early_cleanup() {
    display_surface_unmap();  // no flush here
    wl_display_flush();
}

view_hide() {
    display_early_cleanup();
}
```

And re-use display_surface_unmap in wayland_layer_shell_surface_closed instead of

```
  zwlr_layer_surface_v1_destroy(surface);
  wl_surface_destroy(wayland->surface);
  wayland->wlr_surface = NULL;
  wayland->surface = NULL;
```

**Comment by lbonn** [comment]
Nice, thanks a lot! After a quick test I think it works again with Hyprland.

I just added a small comment on the code organization, let me know what you think.

@LorenzoBettini do you fancy a test as well? :)

**Comment by LorenzoBettini** [comment]
@lbonn yes, I'd like to test it :)
what would be the best way to do that?

**Comment by lbonn** [comment]
@LorenzoBettini 

* `git clone https://github.com/alebastr/rofi -b wayland-window-unmap`
* `git submodule update --init`

Then follow the instructions in https://github.com/lbonn/rofi/blob/wayland/INSTALL.md (only meson will work, not autotools)

eg `meson setup build`, `ninja -C build` ...

File: source/wayland/view.c (hunk 1 above)
Comment (alebastr) [reply source/wayland/view.c]: Done.
Public `display_surface_unmap` is no longer necessary with that approach.

**Comment by LorenzoBettini** [comment]
@lbonn 

here's what I've done:

```
sudo pacman -S meson

cd ~/tmp
git clone https://github.com/alebastr/rofi -b wayland-window-unmap
cd rofi
git submodule update --init

meson setup build
ninja -C build

build/rofi -version
Version: 1.7.5+wayland1-252-gc7472ecc (wayland-window-unmap)
```

Then I tried (with a few windows in separate hyprland workspaces):

```
build/rofi -show window
```

and selecting the window now correctly switches to it (in case, also switching to the corresponding workspaces).

Well done! :)
And thanks for fixing it so fast!

**Comment by lbonn** [comment]
Great! Thanks for your help.

@alebastr is it fine by you if we merge this now?

**Comment by alebastr** [comment]
Thanks for testing!

@lbonn from a brief look, the only public method that touches the surface and does not check it is `display_set_surface_dimensions`. I guess if that becomes a problem, we could fix it later.

Feel free to merge.

**Comment by kRHYME7** [comment]
Thanks!

**Comment by kohane27** [comment]
Just want to show my appreciation that running `paru -S rofi-lbonn-wayland-git` works!

Thank you for fixing it! I really appreciate it!

**Comment by LorenzoBettini** [comment]
Thanks again!
Are you going to release this version?

**Comment by lbonn** [comment]
@LorenzoBettini true, maybe not a bad idea. There have been quite a few fixes since last version.
