### PR TITLE
Fix cursor size

### LINKED ISSUE #20: [BUG] Rofi-lbonn doesn't respect cursor theme & size in sway
## Version

Output of `rofi -v`
Version: 1.6.1-wayland

## Launch Command

`The commandline used to launch **rofi**`
rofi -modi drun -show drun

## Steps to reproduce

run sway
run rofi-lbonn variant in sway

## What behaviour you see

- mouse cursor changes size when hovered over rofi
- mouse cursor theme also changes

## What behaviour you expect to see

- mouse cursor size remains constant
- mouse cursor theme is correctly applied

**Additional details:**

https://user-images.githubusercontent.com/13254332/105858123-44bb2200-5feb-11eb-837c-4cbc74ca72dc.mp4

### PR DESCRIPTION
**Pull request by Sporif**
Default to a size of 24 pixels and use the environment variable XCURSOR_SIZE if it's set.

Closes #20

### CODE REVIEW

File: source/wayland/display.c [hunk 1]
```diff
@@ -1208,8 +1208,18 @@ static gboolean wayland_display_setup(GMainLoop *main_loop,
     return FALSE;
   }
 
+  unsigned cursor_size = 24;
+  char *env_cursor_size = (char *)g_getenv("XCURSOR_SIZE");
+  if (env_cursor_size && strlen(env_cursor_size) > 0) {
+      errno = 0;
+      char *end;
+      unsigned size = strtoul(env_cursor_size, &end, 10);
```
Comment (lbonn) [inline source/wayland/display.c]: There is the glib function `g_ascii_strtoull` that can be used here https://www.freedesktop.org/software/gstreamer-sdk/data/docs/2012.5/glib/glib-String-Utility-Functions.html.

Then we can just check that the return is different from `G_MAXUINT64` and 0 (cursor size of 0 is unlikely...) and avoid messing with errno and `char *end`

Comment (Sporif) [reply source/wayland/display.c]: How about now?

Comment (lbonn) [reply source/wayland/display.c]: Nice, thank you
