### PR TITLE
Fix blurry icon, image and cursor for hidpi

### LINKED ISSUE #45: [BUG] Icons & Cursor Low-Res on Hi-DPI Wayland
### Rofi version (rofi -v)

1.7.2+wayland1

### Configuration

https://gist.github.com/applesud/5abee19a4f85e86ed463b529b577ba7b

### Launch command

rofi -no-config -show-icons -show drun

### Step to reproduce

1. Open sway with an output which has scale set to 2.
2. Run the launch command so that rofi opens on the scaled display.

### Expected behavior

Icons & cursor are shown at the correct resolution.

### Actual behavior

Icons & cursor are shown at a lower resolution (notice how they are less sharp than the text in the attached image).
image

### Additional information

Papirus icon theme.
Icons and cursor were sharp when display was manually scaled (ie. rofi config was adjusted to increase size).
Possibly relevant: cursor seems to be slightly too small on unscaled display, and too large on scaled display.

### PR DESCRIPTION
**Pull request by moetayuko**
fixes #45

The fix is basically trial-and-error so I'm not sure about its correctness tho...

### CODE REVIEW

**Comment by moetayuko** [comment]
@lbonn should pass the CI now. I just don't come up with better ideas to deal with the dependency hell of unit tests

**Comment by lbonn** [comment]
@MoetaYuko thanks for looking into this!

I'll try to check it in the next few days.

**Comment by moetayuko** [comment]
It seems that the value returned by `display_scale()` could change at runtime, need to cache the requested scale in `IconFetcherEntry` and re-fetch the icon when it changes.

**Comment by lbonn** [comment]
@MoetaYuko I think even without dynamic scale changes, this PR is still useful. The changes look good but haven't had time to test it yet. We already have bigger problems with changing screen / resolution: #50.

If you are fine with it we can continue with the merging process.

**Comment by moetayuko** [comment]
This PR consists of two fixes. https://github.com/lbonn/rofi/pull/82/commits/20cd2d446bfb7dd436c39bafd9a03a77529cd21b is fine and should be ready to merge, but https://github.com/lbonn/rofi/pull/82/commits/6f2a9977bab619fc90b0c83a799b1f8b3e8e3906 does not work for @q234rty (ps: it works for me). There seems to be a race condition for him, where `wayland->scale` is used before it gets updated in `wayland_surface_protocol_enter`.

**Comment by moetayuko** [comment]
@lbonn This is working as expected now

**Comment by q234rty** [comment]
Works for me :)

File: source/modes/window.c [hunk 1]
```diff
@@ -1043,20 +1044,21 @@ static cairo_surface_t *get_net_wm_icon(xcb_window_t xid,
...
-  if (c->icon_fetch_size != size) {
+  if (c->icon_fetch_size != size || c->icon_fetch_scale != scale) {
     if (c->icon) {
       cairo_surface_destroy(c->icon);
       c->icon = NULL;
     }
     c->thumbnail_checked = FALSE;
     c->icon_checked = FALSE;
   }
+  // TODO: apply scaling to the following two routines
```
Comment (lbonn) [inline source/modes/window.c:1061]: @MoetaYuko is this actually required? Also, this is the xcb window mode. Was a fix needed here as well? Maybe it can be brought upstream.

Comment (moetayuko) [reply source/modes/window.c:1061]: TBH I don't know their usecases so I marked them to avoid potential ignorance. Can be deleted if you think it's fine to leave them as-is.

Comment (lbonn) [reply source/modes/window.c:1061]: Ok I see. I'll keep anyway for now and make a release as there are a few useful fixes in the main branch since the latest one.
